### ISSUE TITLE
Connect with Democracy NC

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/CampaignFinance#10]
- [x] Zach Ambrose to connect Jeremy Borden to Democracy NC contact
- [x] Jeremy Borden to reach out to Democracy NC to explain project and recruit help
- [x] Jeremy Borden to inquire how much open data the group Democracy NC has gotten from the State Board of Elections

**Comment by jsborden** [comment]
My notes - qs for Bob Hall 
-How used data in the past
-How much data have now/what kind
-Willing to help send out UX surveys or otherwise get involved in project?
-Explain overall goals, get advice

**Comment by jsborden** [comment]
Notes from Bob Hall, our conversation primarily about data quality and need to pull PDFs:

-The data files that Chris downloaded likely does not include scanned PDFs, which are very common for candidates to submit.
-PDF data files have significant challenges - eg donor names not parsed by first, last name. 
-Occupation standardization "terribly complex" given standardization problems and lack of consistency in wording; 
-There are many data quality issues (last names, mispellings, etc) that we will have to overcome in data.
