### ISSUE TITLE
Add Employer Column and Update Column Names to Match the Data Dictionary

### ISSUE THREAD

**Issue by mcelestini** [ncopenpass/CampaignFinance#159]
On the Candidate Page's Contributor Table
- Contribution Type -> Form of Payment
- Contribution Type -> Transaction Type
- Purpose -> Comment

On Search Result's Page Contributor Table
- Add a column for Employer

**Comment by SchaeStewart** [comment]
@mcelestini You listed `Contribution Type` on the Candidate page twice, was that intentional?
