### ISSUE TITLE
Change links to sources in Data Dictionary to embedded hyperlinks

### ISSUE THREAD

**Issue by JMMaok** [ncopenpass/CampaignFinance#191]
Replace Campaign Finance Manual version 12.19 https://s3.amazonaws.com/dl.ncsbe.gov/Campaign_Finance/Campaign%20Finance%20Manual%20Version%2012.19.pdf

with [Campaign Finance Manual version 12.19](https://s3.amazonaws.com/dl.ncsbe.gov/Campaign_Finance/Campaign%20Finance%20Manual%20Version%2012.19.pdf)

This change affects the entries for `Candidate Name`, `Employer Name or Specific Field`, and `Profession or Job Title`.

**Comment by alexisbarnes** [comment]
- And remove extra quotation marks

<img width="1026" alt="Screen Shot 2021-06-22 at 8 08 55 PM" src="https://user-images.githubusercontent.com/16669854/123015161-bed2b580-d395-11eb-92cb-a1a18689fa03.png">
