### ISSUE TITLE
Data Pipeline

### ISSUE THREAD

**Issue by SchaeStewart** [ncopenpass/CampaignFinance#194]
# Data Pipeline

## Background

DB Diagram: https://github.com/ncopenpass/CampaignFinance/blob/master/docs/db_diagram.pdf

Currently we have contribution data from January 2019 until May 2020. This is approximately 470,000 contributions, where a little over half of those are "aggregated individual contributions". We have almost 40,000 contributor records.  

For the committees, we have ~10,000 records. This data was obtained by manually scrapping the State Board of Elections Committees page (link needed)

### What did we do to create this first data set?

1. Downloaded and combined all the contributions for 2019 to May 2020.  
2. Assigned a ID to each "raw_contribution"  
3. Automatically processed the data
   1. Find all raw_contributions with a name and address fuzzy match of 60%. Create a contributor record using one of those matches (the match is basically random), then create the contribution record for each of those matches and assign the contributor id to it
   1. Next we look for raw_contributions that do not have any matches at 30% fuzzy match level, and we create a contributor record and a contribution record for each of those
   1. Finally, we look for raw_contributions that do not have any name/address similarity to any other records, and we create individual contributor + contribution records for each of those
   1. (note: while we did "combine" the contributor information, the original contributor information is still accessible via the raw_contributors table)
4. For the remaining records that could not be automatically processed, we had volunteers manually combine and organize the data
   1. For the manual process, we selected a random unprocessed record from raw_contributions, and found all like (50% fuzzy match) records in the raw_contributions table and in the contributors table.
   2. Volunteers could then choose to associate some or all of the found records with an existing like record, or create a new contributor record
5. Re-added the aggregated individual contributions to the data set

The data cleaning tool can be found in this repo: https://github.com/ncopenpass/campaign-finance-data-cleaning
*This contains the manual data cleaning tool, as well as scripts for loading the data into the DB and processing it*

## Moving Forward

Our goal now is to create an automated data pipeline that can automatically process the data from the board of elections and load it into the dashboard database.

### Guidelines and Technical Requirements

There are some things we should keep in mind as we are building the pipeline

-  ~The pipeline should be almost completely automated. If possible, we do not want to involve volunteers every time more data needs processing~
- There are no major language or framework restrictions. We can use whatever makes sense as long as it is open source and there are people in the project who are familiar with it
  - One caveat, we are using PostgreSQL for the dashboard database, so using that for the data processing probably makes the most sense

### Data Requirements

- The pipeline should continue to automatically process and combine contributors to the best of our ability
  - We can change to a deterministic UUID, if needed. This may help with keeping track of changes over time
- We need some way to track/version data as it changes
  - If an error is discovered in our data (for example two contributors were marked as the same person even though they were not) we need to be able to correct that and leave an audit trail in the database
- We should be able to determine the committee type (either candidate committee or corporate committee)
  - We may be able to determine this based on if a committee has a candidate field (like candidate_name)
- We may need to move candidate information from the committee table into its own candidate table
  - Currently, the committee table contains
- We should be able to see committee to committee contributions using their NC State Board of Elections ID (NCSBE ID)
  - The contributions data we receive from the board of elections only has the receiving entities NCSBE ID. Ideally, we want to be able to track the NCBE ID giving the donation as well as the one receiving it. We may be able to use the `contributions.transaction_type` field to determine this information
- We should be able to track committees from year to year
  - Each year/election cycle (I'm not sure which) candidates must create a new committee, we need to be able to track this.
  - Some investigation shows that the State Board of Elections ID assigned to each committee is logical and might increment year to year

**Comment by jsborden** [comment]
Do we need a similar discussion of expenditure data (not yet included)? This shouldn't be as hard but of course we won't know until we start processing.
