### ISSUE TITLE
Bug: `NaN - NaN Contributions`

### ISSUE THREAD

**Issue by SchaeStewart** [ncopenpass/CampaignFinance#206]
![image](https://user-images.githubusercontent.com/9397068/108925755-3290cb80-760b-11eb-86ce-9f8479c9ad20.png)

At the bottom of the table `NaN - NaN Contributions` is shown.

https://campaign-finance-dashboard.herokuapp.com/candidate/STA-C0498N-C-002

**Comment by brandon-irl** [comment]
Duplicate of #201?

**Comment by SchaeStewart** [comment]
@brandon-irl Yes it is. I should've checked before I opened it
