### ISSUE TITLE
Candidate Page: Candidate Info, Donors Table, and Download Results Button

### ISSUE THREAD

**Issue by alexisbarnes** [ncopenpass/CampaignFinance#32]
https://www.figma.com/file/OcC48DWJjwCsPigGa9vb82/Campaign-Finance-Dashboard-Wireframes?node-id=2%3A58

Donors Table has filter options for each column.

**Comment by alexisbarnes** [comment]
Make a candidate info component. 
Need a new table component (and include additional filter options and download results button)? 
Total funding component?
Additional items may be added to this page...

**Comment by mcelestini** [comment]
moved this from `In Progress` to `Under Review` by mistake. Didn't realize the PR was WIP, my b
