### ISSUE TITLE
About Page Redesign

### ISSUE THREAD

**Issue by alexisbarnes** [ncopenpass/CampaignFinance#46]
Waiting on design

**Comment by dsolowitz** [comment]
Do we have any info laying around that we want to put in the about page? Otherwise, I can start adding the route and the page.

**Comment by SchaeStewart** [comment]
@dsolowitz I think we are still waiting on a design

**Comment by alexisbarnes** [comment]
@dsolowitz @SchaeStewart We now have a design: https://www.figma.com/file/OcC48DWJjwCsPigGa9vb82/Campaign-Finance-Dashboard-Wireframes?node-id=2%3A58

It's real basic right now for the MVP. Probably will add more structure to it later.

**Comment by alexisbarnes** [comment]
We'll revisit this post-MVP.
