### ISSUE TITLE
Data Dictionary and Glossary Pages

### ISSUE THREAD

**Issue by alexisbarnes** [ncopenpass/CampaignFinance#48]
Waiting on content and design

**Comment by mcelestini** [comment]
Added the following for the data dictionary page, based off the following spreadsheet
![image](https://user-images.githubusercontent.com/39271238/89593491-4dd9ec00-d81d-11ea-9ba6-c21fdbc27825.png)

but I'm not really sure what to do for the Glossary page. I didn't see a mock up for that one
