### ISSUE TITLE
Add User Analytics

### ISSUE THREAD

**Issue by alexisbarnes** [ncopenpass/CampaignFinance#50]
Shaun suggested looking into Hot Jar

**Comment by shaunman** [comment]
There's a free version that would be useful once we get the MVP out to the public.

https://www.hotjar.com/

**Comment by funkybunch** [comment]
I'd recommend coupling this with Google Tag manager.  Hotjar can be implemented through GTM among other analytics platforms.  I can take this one.

**Comment by funkybunch** [comment]
Adding this for reference: https://help.hotjar.com/hc/en-us/articles/115009499708-Google-Tag-Manager-
