### ISSUE TITLE
Aggregate search for Donor, Candidate, and PAC

### ISSUE THREAD

**Issue by SchaeStewart** [ncopenpass/CampaignFinance#59]
Utilized the existing search functions to create an aggregate search endpoint. Probably structure a response like this:

```json
{
  "pac": [],
  "donor": [],
  "candidate": []
}
```

Ensure route supports pagination.

PAC data isn't available yet. For now just return empty data

**Comment by benjaminEwhite** [comment]
@SchaeStewart can you provide more detail on this one. Is the idea that this endpoint allows you to search for a pac, donor, and candidate all in one request?

**Comment by SchaeStewart** [comment]
Yes that's the idea. If you look at the wireframe, the initial search bar, searches all of those data types.  https://www.figma.com/proto/OcC48DWJjwCsPigGa9vb82/Campaign-Finance-Dashboard-Wireframes?node-id=2%3A59&viewport=-1320%2C-986%2C0.3811715841293335&scaling=scale-down-width

**Comment by benjaminEwhite** [comment]
@SchaeStewart not totally obvious to me how this endpoint should handle pagination given that it's stitching together 3 types of entities. 

One way we might do this is like this:

```json
{
  "data": 
    {
      "type": "candidate",
      "content": {
        "candidate_last_name": "ABERNETHY",
        "candidate_first_name": "RICHARD",
        "candidate_middle_name": "BRUCE",
      }
    },
    {
      "type": "donor",
      "content": {
        "id": "<some-id>",
        "name": "Adam Apple",
        "city": "city",
        "state": "NC",
        "zip_code": "27103",
        "profession": "PHYSICIAN",
        "employer_name": "NOVANT HEALTH UROLOGY PARTNERS",
        "sml": 0.6875
      }
      ...
    }
  ],
  "count": "some value"
}
```


Thoughts?

**Comment by SchaeStewart** [comment]
I think we can probably skip the pagination for this route and just limit the results. My thought is, this endpoint will support getting the table data in this view: https://www.figma.com/proto/OcC48DWJjwCsPigGa9vb82/Campaign-Finance-Dashboard-Wireframes?node-id=2%3A277&viewport=-1320%2C-986%2C0.3811715841293335&scaling=scale-down-width

If the user wants to go past to first page of results, we should probably just push them to the page they are interested in. For example, if they are looking at the candidates tab, and they want to see more candidates, we would just redirect them to a candidates page

**Comment by SchaeStewart** [comment]
Did you want me to assign this one to you?

**Comment by benjaminEwhite** [comment]
Yeah i can do this one.
