### ISSUE TITLE
Route to get list of donations for a given contributor

### ISSUE THREAD

**Issue by SchaeStewart** [ncopenpass/CampaignFinance#60]
This route should return a list of contributions for a given contributorID.  

Ensure route works wit Pagination. You can look at other existing routes, for an example. Other ideas are welcome.

**Comment by SchaeStewart** [comment]
@benjaminewhite is currently assigned. (I'm unable to add contributors to the team as of now)

**Comment by benjaminEwhite** [comment]
@SchaeStewart realized this feature request is unclear to me. Is this meant to return all donations for a given candidate, given their id (as per the issue title), or is it meant to show all contributions for a particular contributor (as per the main body of the issue text)?

**Comment by SchaeStewart** [comment]
@benjaminEwhite My bad. It should be for donations for a given contributor
